# Generated by Django 3.0.5 on 2020-05-10 05:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='name', editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='family',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='name', editable=False, populate_from='name'),
        ),
    ]
