# Generated by Django 3.0.5 on 2020-05-10 06:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200510_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
    ]
