# Generated by Django 3.0.5 on 2020-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_companyinvite_familyinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyinvite',
            old_name='company',
            new_name='family',
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
