# Generated by Django 3.0.5 on 2020-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20200512_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvite',
            name='accepted',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='familyinvite',
            name='accepted',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
